# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-23 16:21
# !By running makemigrations, you’re telling Django that you’ve made some changes to your models (in this case, you’ve made new ones) and that you’d like the changes to be stored as a migration.
# When running `python manage.py makemigrations polls`, the migrations are how Django stores changes to your models, and you can read the migration for your new model if you like. 
# !The sqlmigrate command doesn’t actually run the migration on your database - it just prints it to the screen so that you can see what SQL Django thinks is required.
# TODO: TO check for any problems in your project without making migrations or touching the database run the script `python manage.py check`
# The migrate command takes all the migrations that haven’t been applied  essentially, synchronizing the changes you made to your models with the schema in the database.
# !Migrations are very powerful and it specializes in upgrading your database live, without losing data.
# TODO: 1.) Change your models (in models.py).
# TODO: 2.) Run python manage.py makemigrations to create migrations for those changes
# TODO: 3.) Run python manage.py migrate to apply those changes to the database.

from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
